armbian-update: add kernel rescue method(-r)

diff --git a/build-armbian/armbian-files/common-files/usr/sbin/armbian-update b/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
--- a/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
+++ b/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
@@ -17,11 +17,13 @@
 # Optional parameter meaning: -k = set the kernel name
 #                             -v = set the kernel version branch
 #                             -m = ues mainline_u-boot
+#                             -r = Rescue the kernel
 #
 # Command optional parameters:   armbian-update -k 5.15.50 -v stable/dev -m yes/no
 # Set the kernel name command:   armbian-update -k 5.15.50
 # Set the kernel branch command: armbian-update -v dev
-# Use mainline u-boot command:   armbian-update -m yes
+# Use mainline u-boot command:   armbian-update -m yes/no
+# Rescue the Armbian kernel:     armbian-update -r
 #
 #========================================= Functions list =========================================
 #
@@ -29,8 +31,10 @@
 # check_depends      : Check dependencies
 # get_textoffset     : Get kernel TEXT_OFFSET
 # init_var           : Initialize all variables
+# rescue_kernel      : Rescue the kernel
 # download_kernel    : Download the kernel
 # check_kernel       : Check kernel files list
+# backup_kernel      : Backup current kernel
 # update_kernel      : Update the kernel
 # update_uboot       : Update the uboot
 #
@@ -38,6 +42,10 @@
 #
 # Set current path
 current_path="${PWD}"
+# Set kernel backup directory
+backup_path="/ddbr/backup"
+# Set kernel rescue temporary directory
+rescue_path="/ddbr/rescue"
 # Set the release check file
 lasthinker_release_file="/etc/lasthinker-release"
 # Set the kernel download repository
@@ -46,7 +54,7 @@ kernel_repo="https://github.com/lasthinker/kernel/tree/main/pub"
 kernel_dir=("stable" "rk3588" "dev")
 # Set default installation mainline u-boot (-m)
 auto_mainline_uboot="no"
-#
+
 # Set font color
 STEPS="[\033[95m STEPS \033[0m]"
 INFO="[\033[94m INFO \033[0m]"
@@ -202,12 +210,85 @@ init_var() {
     sync && echo ""
 }
 
+# Rescue the kernel
+rescue_kernel() {
+    echo -e "${STEPS} Start rescuing kernel files..."
+
+    # Check the current system running disk
+    root_devname="$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')"
+    if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
+        error_msg "You are running in eMMC mode, please boot system with usb or tf card!"
+    fi
+
+    # Find emmc disk, first find emmc containing boot0 partition
+    box_disk="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")"
+    # Find emmc disk, find emmc that does not contain the boot0 partition
+    [[ -z "${box_disk}" ]] && box_disk="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?)' | grep -vE ^${root_devname} | uniq)"
+    # Find NVMe disk
+    [[ -z "${box_disk}" ]] && box_disk="$(lsblk -l -o NAME | grep -oE '(nvme0n1)' | grep -vE ^${root_devname} | uniq)"
+    # Check if emmc exists
+    [[ -z "${box_disk}" ]] && error_msg "The eMMC/NVMe storage not found in this device!"
+    # Location of disk
+    rescue_disk="/dev/${box_disk}"
+    echo -e "${INFO} The device eMMC/NVMe name: [ ${rescue_disk} ]"
+
+    # Check if there is enough free space
+    available_space="$(df -Tk / | grep '/dev/' | awk '{print $5}' | echo $(($(xargs) / 1024 / 1024)))"
+    [[ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]] && error_msg "The remaining space cannot be obtained."
+    [[ "${available_space}" -lt "3" ]] && error_msg "The available space is less than 3GiB, please use [ armbian-tf ] to expand the USB."
+
+    # Create a temporary mount directory
+    rm -rf ${rescue_path}
+    mkdir -p ${rescue_path}/{bootfs/,rootfs/}
+
+    # Mount eMMC to USB
+    mount ${rescue_disk}p1 ${rescue_path}/bootfs
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${rescue_disk}p1 failed!"
+    mount ${rescue_disk}p2 ${rescue_path}/rootfs
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${rescue_disk}p2 failed!"
+
+    # Identify the current kernel files
+    kernel_signature="$(uname -r)"
+
+    # 01. For /boot files
+    cd ${rescue_path}/bootfs
+    rm -rf config-* initrd.img-* System.map-* vmlinuz-* uInitrd* *Image dtb*
+    [[ "${PLATFORM}" == "amlogic" ]] && cp -rf /boot/{u-boot.ext,u-boot.emmc} -t . 2>/dev/null
+    cp -rf /boot/{*-${kernel_signature},uInitrd,*Image,dtb} -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(1/3) [ boot ] kernel files rescue failed."
+    echo -e "${INFO} (1/3) [ boot ] kernel files rescue succeeded."
+
+    # 02. For /usr/lib/modules/${kernel_signature}
+    cd ${rescue_path}/rootfs/usr/lib/modules
+    rm -rf *
+    cp -rf /usr/lib/modules/${kernel_signature} -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(2/3) [ modules ] kernel files rescue failed."
+    echo -e "${INFO} (2/3) [ modules ] kernel files rescue succeeded."
+
+    # 03. For /usr/src/linux-headers-${kernel_signature}
+    cd ${rescue_path}/rootfs/usr/src
+    rm -rf linux-headers-*
+    cp -rf /usr/src/linux-headers-${kernel_signature} -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(3/3) [ headers ] kernel files rescue failed."
+    echo -e "${INFO} (3/3) [ headers ] kernel files rescue succeeded."
+
+    # Unmount the emmc partition
+    cd ${rescue_path}
+    umount -f ${rescue_path}/bootfs
+    [[ "${?}" -ne "0" ]] && error_msg "Failed to umount [ ${rescue_path}/bootfs ]"
+    umount -f ${rescue_path}/rootfs
+    [[ "${?}" -ne "0" ]] && error_msg "Failed to umount [ ${rescue_path}/rootfs ]"
+
+    sync && echo ""
+}
+
 # Download the kernel
 download_kernel() {
     cd ${current_path}
     echo -e "${STEPS} Start downloading kernel..."
 
     # Query the current version
+    current_kernel_signature="$(uname -r)"
     current_kernel="$(echo "$(uname -r)" | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')"
     [[ -z "${current_kernel}" ]] && error_msg "Failed to query the current kernel version."
     # kernel_verpatch, such as [ 5.10 ]
@@ -306,6 +387,61 @@ check_kernel() {
     sync && echo ""
 }
 
+# Backup current kernel
+backup_kernel() {
+    echo -e "${STEPS} Start backing up the current kernel..."
+
+    # Identify the current kernel files
+    rm -rf ${backup_path}/${current_kernel}
+    mkdir -p ${backup_path}/${current_kernel}
+
+    # Create temporary file directory
+    kernel_tmp_path="$(mktemp -d)"
+    cd ${kernel_tmp_path}
+
+    # 1. Pack the boot-*.tar.gz file
+    rm -rf *
+    cp -rf /boot/*-${current_kernel_signature} -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(1/4) Failed to copy [ /boot/*-${current_kernel_signature} ] files."
+    rm -rf dtb*
+    chmod +x *
+    tar -czf boot-${current_kernel_signature}.tar.gz *
+    mv -f *.tar.gz ${backup_path}/${current_kernel}
+    echo -e "${INFO} (1/4) The [ boot-${current_kernel_signature}.tar.gz ] backup successful."
+
+    # 2. Pack the dtb-*.tar.gz file
+    rm -rf *
+    cp -rf /boot/dtb/${PLATFORM}/* -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(2/4) Failed to copy [ /boot/dtb/${PLATFORM}/* ] files."
+    tar -czf dtb-${PLATFORM}-${current_kernel_signature}.tar.gz *
+    mv -f *.tar.gz ${backup_path}/${current_kernel}
+    echo -e "${INFO} (2/4) The [ dtb-${PLATFORM}-${current_kernel_signature}.tar.gz ] backup successful."
+
+    # 3. Pack the header-*.tar.gz file
+    rm -rf *
+    cp -rf /usr/src/linux-headers-${current_kernel_signature}/* -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(3/4) Failed to copy [ /usr/src/linux-headers-${current_kernel_signature}/* ] files."
+    tar -czf header-${current_kernel_signature}.tar.gz *
+    mv -f *.tar.gz ${backup_path}/${current_kernel}
+    echo -e "${INFO} (3/4) The [ header-${current_kernel_signature}.tar.gz ] backup successful."
+
+    # 4. Pack the modules-*.tar.gz file
+    rm -rf *
+    cp -rf /usr/lib/modules/${current_kernel_signature} -t .
+    [[ "${?}" -ne "0" ]] && error_msg "(4/4) Failed to copy [ /usr/lib/modules/${current_kernel_signature} ] files."
+    tar -czf modules-${current_kernel_signature}.tar.gz *
+    mv -f *.tar.gz ${backup_path}/${current_kernel}
+    echo -e "${INFO} (4/4) The [ modules-${current_kernel_signature}.tar.gz ] backup successful."
+
+    # Add sha256sum integrity verification file
+    cd ${backup_path}/${current_kernel}
+    sha256sum * >sha256sums
+    echo -e "${INFO} The [ sha256sums ] file has been generated"
+    echo -e "${INFO} The current kernel backup path: [ ${backup_path}/${current_kernel} ]. It can be deleted if it is not needed."
+
+    sync && echo ""
+}
+
 # Update the kernel
 update_kernel() {
     cd ${kernel_path}
@@ -376,6 +512,7 @@ update_uboot() {
         dd if="${BOOTLOADER_IMG}" of="${DEV_EMMC}" conv=fsync bs=1 count=444 2>/dev/null
         dd if="${BOOTLOADER_IMG}" of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1 2>/dev/null
     fi
+    [[ "${?}" -eq "0" ]] || error_msg "Failed to write bootloader using [ dd ]."
 
     sync && echo ""
 }
@@ -383,20 +520,19 @@ update_uboot() {
 # Check script permission
 [[ "$(id -u)" == "0" ]] || error_msg "Please run this script as root: [ sudo $0 ]"
 echo -e "${STEPS} Welcome to the kernel update tool."
-#
-# Check dependencies
-check_depends
-# Initialize all variables
-init_var "${@}"
-# Download the kernel
-download_kernel
-# Check kernel files list
-check_kernel
-# Update the kernel
-update_kernel
-# Update the uboot for Amlogic Boxes
-[[ "${PLATFORM}" == "amlogic" ]] && update_uboot
-#
+
+if [[ "${1}" == "-r" ]]; then
+    rescue_kernel
+else
+    check_depends
+    init_var "${@}"
+    download_kernel
+    check_kernel
+    backup_kernel
+    update_kernel
+    [[ "${PLATFORM}" == "amlogic" ]] && update_uboot
+fi
+
 sync && sleep 3
 echo -e "${SUCCESS} Successfully updated, automatic restarting..."
 reboot
