Remove desktop options

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -9,14 +9,13 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      sel_tags_keywords:
+      set_release:
         description: "Select OS Release."
         required: false
         default: "bullseye"
         type: choice
         options:
           - jammy
-          - focal
           - bullseye
       armbian_soc:
         description: "Select Amlogic SoC."
@@ -53,6 +52,10 @@ on:
         options:
           - ext4
           - btrfs
+      armbian_sign:
+        description: "Set armbian custom name."
+        required: false
+        default: ""
 
 env:
   TZ: America/New_York
@@ -67,6 +70,7 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Initialization Environment
+        id: init
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
@@ -77,38 +81,28 @@ jobs:
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
           echo "COMPILE_STARTINGTIME=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
+          echo "::set-output name=status::success"
 
       - name: Download Armbian from Releases
         id: down
         if: (!cancelled())
         run: |
           armbian_buildpath="build/output/images"
-          [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
+          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"
           down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
-          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
-          #
+          down_path="Armbian_Aml_${{ github.event.inputs.set_release }}.*/Armbian_.*-trunk_.*.img.gz"
+
           # down_filename: Armbian_Aml_bullseye_gnome_desktop_05.17.1924/Armbian_22.05.0-trunk_Odroidn2_bullseye_current_5.10.110.img.gz
           down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
           down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
-          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          [[ -z "${down_file}" ]] && echo "Invalid download file." && exit 1
           wget -q -P "${armbian_buildpath}" "${down_file}" && sync
           cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
-          #
-          # down_tag: Armbian_Aml_bullseye_gnome_desktop
-          down_tag="${down_filename%%/*}" && down_tag="${down_tag%_*}"
-          echo "ARMBIAN_RELEASE=${down_tag}" >> $GITHUB_ENV
-          #
-          # down_board: bullseye
-          down_board="$(echo ${down_tag} | cut -d"_" -f3)"
-          echo "ARMBIAN_BOARD=${down_board}" >> $GITHUB_ENV
-          #
-          # down_edition: gnome_desktop
-          down_edition="$(echo ${down_tag} | cut -d"_" -f4-)"
-          echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
-          #
+
+          echo "ARMBIAN_RELEASE=${{ github.event.inputs.set_release }}" >> $GITHUB_ENV
           echo "::set-output name=status::success"
 
-      - name: Rebuild Armbian [ Board is ${{ env.ARMBIAN_BOARD }} / Edition is ${{ env.ARMBIAN_DESKTOP_OPT }} ]
+      - name: Rebuild Armbian [ ${{ env.ARMBIAN_RELEASE }} ]
         uses: lasthinker/amlogic-s9xxx-armbian@main
         if: steps.down.outputs.status == 'success' && !cancelled()
         with:
@@ -119,21 +113,20 @@ jobs:
           auto_kernel: ${{ github.event.inputs.auto_kernel }}
           armbian_size: ${{ github.event.inputs.armbian_size }}
           armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
-          armbian_sign: _${{ env.ARMBIAN_DESKTOP_OPT }}
+          armbian_sign: ${{ github.event.inputs.armbian_sign }}
 
       - name: Upload Armbian Image to Release
         uses: ncipollo/release-action@main
         if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: ${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: Armbian_Aml_${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
           body: |
-            This is Armbian Image for Amlogic S905X
-            * Firmware Information
-            Default Username: root
-            Default Password: 1234
-            Install to eMMC Command: armbian-install
-            Update Command: armbian-update
-            Edition: ${{ env.ARMBIAN_DESKTOP_OPT }}
+            This is Armbian image for Amlogic S905X
+            * Firmware information
+            Default username: root
+            Default password: 1234
+            Install command: armbian-install
+            Update command: armbian-update
